# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/dishaa34/flyrank-ml/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

## Unit of Analysis

One row represents one content page (or URL) for a single monthly snapshot in the warehouse dataset.

For this assignment, I use the month **2026-03** as the analysis window because it is a mid-panel month. Using a mid-panel month allows feature engineering without using the final month of the dataset, which is reserved as a future outcome period.

The goal is to study historical content performance for identifying pages that may benefit from a content refresh.

In [13]:
import pandas as pd

df = pd.read_csv("/content_refresh_anonymized.csv")

print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

df.head()

Number of rows: 28060
Number of columns: 44

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [14]:
import pandas as pd

df = pd.read_csv("/content_refresh_anonymized.csv")

print("Rows:", len(df))
print("Columns:", len(df.columns))

df.head()

Rows: 28060
Columns: 44

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [15]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

## Features, Label, Context, Excluded

### Features
- impressions_90d
- clicks_90d
- sessions_90d
- avg_position
- engagement_rate

These features are historical measurements and are available before making a content refresh decision.

### Label (Proxy)
- trend_pct

This is used as a proxy for future content performance.

### Context
- content_id
- client_id
- content_type

These identify or describe the content but are not used as predictive features.

### Excluded
- trend_direction

This field is excluded because it is derived from the target trend and may introduce data leakage.

In [16]:
feature_cols = [
    "impressions_90d",
    "clicks_90d",
    "sessions_90d",
    "avg_position",
    "engagement_rate"
]

print(df[feature_cols].head())

   impressions_90d  clicks_90d  sessions_90d  avg_position  engagement_rate
0           3803.0        29.0          17.0          10.6             5.88
1          15320.0         7.0           9.0          20.3             0.00
2          12581.0        11.0          11.0          36.5             0.00
3          11751.0        58.0          78.0           6.2             1.28
4          19140.0        24.0         145.0          44.0             0.00

In [17]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

## Verification Queries

The following checks verify the data contract.

1. Verify that each row represents one unique content item.

2. Verify the total number of rows and columns.

3. Check for missing values in the selected feature columns.

In [18]:
print("===== Query 1: Grain =====")
print("Rows:", len(df))
print("Unique content_id:", df["content_id"].nunique())

print("\n===== Query 2: Dataset Size =====")
print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\n===== Query 3: Missing Values =====")
print(df[feature_cols].isnull().sum())

===== Query 1: Grain =====
Rows: 28060
Unique content_id: 28060

===== Query 2: Dataset Size =====
Rows: 28060
Columns: 44

===== Query 3: Missing Values =====
impressions_90d    1
clicks_90d         1
sessions_90d       1
avg_position       1
engagement_rate    1
dtype: int64

## Feature Frame

| Feature | Available when? |
|----------|-----------------|
| impressions_90d | Available because it comes from historical Search Console data collected before the refresh decision. |
| clicks_90d | Available because it records historical clicks before the decision point. |
| sessions_90d | Available because it measures historical Analytics sessions. |
| avg_position | Available because historical ranking position is known before deciding to refresh content. |
| engagement_rate | Available because it summarizes previous user engagement. |

In [19]:
feature_frame = df[
    [
        "impressions_90d",
        "clicks_90d",
        "sessions_90d",
        "avg_position",
        "engagement_rate"
    ]
]

feature_frame.head()

   impressions_90d  clicks_90d  sessions_90d  avg_position  engagement_rate
0           3803.0        29.0          17.0          10.6             5.88
1          15320.0         7.0           9.0          20.3             0.00
2          12581.0        11.0          11.0          36.5             0.00
3          11751.0        58.0          78.0           6.2             1.28
4          19140.0        24.0         145.0          44.0             0.00

## Leakage Experiment

I deliberately added **trend_direction** to the feature set.

This column is derived from the outcome represented by **trend_pct**, so it leaks future information into the model.

A model using this feature would appear unrealistically accurate.

After removing **trend_direction**, the remaining feature set represents information that would genuinely be available at the decision time.

In [20]:
from sklearn.linear_model import LinearRegression

# Honest features
X = df[
    [
        "impressions_90d",
        "clicks_90d",
        "sessions_90d",
        "avg_position",
        "engagement_rate"
    ]
]

y = df["trend_pct"]

print("Honest feature matrix shape:", X.shape)

# Deliberately leaked feature
X_leak = X.copy()
X_leak["trend_direction"] = pd.factorize(df["trend_direction"])[0]

print("Feature matrix with leakage:", X_leak.shape)

# Remove leakage
X_fixed = X_leak.drop(columns=["trend_direction"])

print("Leakage removed.")
print("Final feature matrix shape:", X_fixed.shape)

Honest feature matrix shape: (28060, 5)
Feature matrix with leakage: (28060, 6)
Leakage removed.
Final feature matrix shape: (28060, 5)

In [21]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

## Data Limits

This dataset is an anonymized warehouse snapshot rather than a complete longitudinal warehouse.

It cannot explain why content performance changes or establish causal relationships.

The analysis is intended to support content refresh decisions using historical observations only.

In [22]:
print("Missing values by column:")

df.isnull().sum().sort_values(ascending=False).head(10)

Missing values by column:

provider_used        20079
word_count_tier       7208
char_count_tier       7208
word_count            7207
char_count            7207
model_used            5369
trend_pct             3176
competition_level     2446
search_volume         2311
cpc                   2311
dtype: int64

In [23]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.